function PLOT_annotations(  SOURCE, ParticipantList , dataParticipant )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

SOURCE.CodingSchemaFile = fullfile(...
    SOURCE.experimentDataFolder,...
    'codingSchema.json');

codingSchema = loadjson(SOURCE.CodingSchemaFile);

for iEvent = 1 : length(SOURCE.EventType)
    for iParticipant = 1 : length(ParticipantList)
        figure('name', sprintf('Event %s - Participant %s', SOURCE.EventType{iEvent}, ParticipantList{iParticipant}),...
            'position', [200  100  500  300], ...
            'numbertitle', 'off');
        
        toBeLoaded_ANNOTATION = fullfile(SOURCE.dataParticipantsFolder,...
            ParticipantList{iParticipant}, ...
            sprintf('annotation_%s_%s.mat', ParticipantList{iParticipant}, SOURCE.EventType{iEvent}));
        
        if exist(toBeLoaded_ANNOTATION, 'file') == 2
            LOADED_ANNOTATION = load(toBeLoaded_ANNOTATION);
            
            for iAnn = 1 : length(codingSchema.schema)
                subplot(length(codingSchema.schema), 1, iAnn  )
                
                set(gca,...
                    'units', 'normalized',...
                    'xtick', [1 : 50 : dataParticipant(iParticipant).EventLength],...
                    'xticklabel', ([1 : 50 : dataParticipant(iParticipant).EventLength] - dataParticipant(iParticipant).IDX_warning) ./10,...
                    'ytick', [0:length(codingSchema.schema{iAnn}.categories)-1],...
                    'YtickLabel', codingSchema.schema{iAnn}.categories, ...
                    'xlim', [1 dataParticipant(iParticipant).EventLength], ...
                    'ylim', [-0.5 length(codingSchema.schema{iAnn}.categories)- 0.5], ...
                    'Box', 'on',...
                    'visible', 'on',...
                    'ygrid', 'on')
                
                H_line_annotations = line('XData', 1:dataParticipant(iParticipant).EventLength,...
                    'YData', LOADED_ANNOTATION.annotations.(codingSchema.schema{iAnn}.variable),...
                    'parent', gca, ...
                    'Linewidth', 1);
                
                title(sprintf('Annotations of %s', codingSchema.schema{iAnn}.variable))
                ylabel(sprintf('ID: %s', ParticipantList{iParticipant}));
                xlabel('Time relative to warning onset [s]')
                
                axList = findobj(gcf, 'type', 'axes');
                set(axList,...
                    'fontsize', 8, ...
                    'LabelFontSizeMultiplier', 1)
            end
        else
            warning('!!! %s not found !!! ', toBeLoaded_ANNOTATION)
            continue
        end
    end
end



end

